# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
